baseurl = "http://xbuf.github.io/"
languageCode = "en-us"
title = "xbuf"
theme = "site0"
canonifyurls = true

[params]
  Description = "An exchange format for 3D scenes, models, animations, …"
  Author = "David Bernard"
  Copyright = "Public domain (CC0-1.0)"
